server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/urlshortener?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  security:
    oauth2:
      client:
        provider:
          urlshortener-keycloak-provider:
            issuer-uri: http://localhost:8080/realms/${keycloak.realm}
