server:
  port: 8081

app:
  url: http://localhost:${server.port}

keycloak:
  k8s-external-url: http://localhost:8080

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/urlshortener?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
  security:
    oauth2:
      client:
        provider:
          urlshortener-keycloak-provider:
            issuer-uri: ${keycloak.k8s-external-url}/realms/${keycloak.realm}
