apiVersion: v1
kind: Service
metadata:
  name: urlshortener-db-service
  namespace: urlshortener-dev
  labels:
    app: urlshortener
    layer: db
spec:
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: urlshortener
    layer: db
  type: ClusterIP
