apiVersion: v1
kind: Service
metadata:
  name: urlshortener-keycloak-service
  namespace: urlshortener-dev
  labels:
    app: urlshortener
    layer: keycloak
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30009
  selector:
    apps: urlshortener
    layer: keycloak
  type: NodePort
  
