apiVersion: v1
kind: Pod
metadata:
  name: urlshortener-db-pod
  labels:
    app: urlshortener
    layer: db
spec:
  containers:
  - image: urlshortener-db:latest
    name: urlshortener-db-container
    resources: {}
    ports:
    - containerPort: 3306
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: root
    imagePullPolicy: IfNotPresent
